"""Multipole decomposition of Wannier Hamiltonians."""

from __future__ import annotations

from pathlib import Path

import h5py
import numpy as np

from .multipole import SparseCOO
from .wannier_utils.hamiltonian import HamR


class MultipoleMatrixReader:
    """Read HDF5 files generated by `Multipole.write_hdf5`."""

    def __init__(self, path: Path | str):
        self.path = Path(path)
        self.h5 = h5py.File(self.path, "r")
        self.grp = self.h5["multipole_matrix"]
        self.shape = tuple(int(x) for x in self.grp["shape"][:])
        self.irvec = self.grp["irvec"][:]
        self.coords = self.grp["coords"][:]
        self.data = self.grp["data"][:]
        self.index = self.grp["multipole_index"][:]

    def close(self) -> None:
        self.h5.close()

    def __enter__(self) -> "MultipoleMatrixReader":
        return self

    def __exit__(self, *_exc_info) -> None:
        self.close()

    @property
    def num_multipole(self) -> int:
        return int(self.shape[0])

    @property
    def num_wann(self) -> int:
        return int(self.shape[2])

    def get_component(self, im: int) -> SparseCOO:
        start = int(self.index[im])
        end = int(self.index[im + 1])
        coords = self.coords[1:, start:end]
        data = self.data[start:end]
        return SparseCOO(coords=coords, data=data, shape=self.shape[1:])


class MultipoleDecomposition:
    """Decompose a Hamiltonian into a precomputed multipole basis."""

    def __init__(
        self,
        ham_r: HamR,
        multipole_path: Path | str,
        initial_ket: list[str] | None = None,
        final_ket: list[str] | None = None,
    ):
        self.ham_r = ham_r
        self.irvec = ham_r.irvec
        self.ndegen = ham_r.ndegen
        self.nrpts = ham_r.nrpts
        self.num_wann = ham_r.num_wann
        self.multipole_path = Path(multipole_path)

        with MultipoleMatrixReader(self.multipole_path) as reader:
            if reader.num_wann != self.num_wann:
                raise ValueError(
                    f"Orbital mismatch: multipole has {reader.num_wann}, "
                    f"Hamiltonian has {self.num_wann}."
                )
            self.num_multipole = reader.num_multipole
            self.z_coefficients = np.zeros(self.num_multipole, dtype=np.complex128)
            coords_parts: list[np.ndarray] = []
            data_parts: list[np.ndarray] = []

            for im in range(self.num_multipole):
                component = reader.get_component(im)
                if initial_ket is not None and final_ket is not None:
                    component = self.change_orbital_order(component, initial_ket, final_ket)
                if not np.array_equal(reader.irvec, self.irvec):
                    component = self.pad_irvec(self.irvec, reader.irvec, component)
                self.z_coefficients[im] = self.decompose_ham(ham_r.hrs, component)
                if component.nnz:
                    im_axis = np.full((1, component.nnz), im, dtype=np.int64)
                    coords_parts.append(np.vstack([im_axis, component.coords]))
                    data_parts.append(component.data)

        if coords_parts:
            self.coords = np.hstack(coords_parts)
            self.data = np.concatenate(data_parts)
        else:
            self.coords = np.empty((4, 0), dtype=np.int64)
            self.data = np.empty(0, dtype=np.complex128)
        self.shape = (self.num_multipole, self.nrpts, self.num_wann, self.num_wann)

    @staticmethod
    def change_orbital_order(
        component: SparseCOO,
        initial_ket: list[str],
        final_ket: list[str],
    ) -> SparseCOO:
        """Reorder orbital axes from `initial_ket` to `final_ket`."""

        if sorted(initial_ket) != sorted(final_ket):
            raise ValueError("initial_ket and final_ket must contain the same labels.")
        initial_index = {state: idx for idx, state in enumerate(initial_ket)}
        reorder_indices = np.array([initial_index[state] for state in final_ket])
        inverse = np.empty_like(reorder_indices)
        inverse[reorder_indices] = np.arange(len(reorder_indices))
        coords = component.coords.copy()
        coords[1] = inverse[component.coords[1]]
        coords[2] = inverse[component.coords[2]]
        return SparseCOO(coords=coords, data=component.data, shape=component.shape)

    @staticmethod
    def pad_irvec(target_irvec: np.ndarray, source_irvec: np.ndarray, component: SparseCOO) -> SparseCOO:
        """Pad or reorder the real-space axis to match a target `irvec` list."""

        source_vectors = [tuple(vec) for vec in source_irvec]
        target_index = {tuple(vec): idx for idx, vec in enumerate(target_irvec)}
        coords_rows: list[list[int]] = [[], [], []]
        data: list[np.complex128] = []
        for i in range(component.nnz):
            source_r = source_vectors[int(component.coords[0, i])]
            if source_r not in target_index:
                continue
            coords_rows[0].append(target_index[source_r])
            coords_rows[1].append(int(component.coords[1, i]))
            coords_rows[2].append(int(component.coords[2, i]))
            data.append(component.data[i])
        return SparseCOO(
            coords=np.array(coords_rows, dtype=np.int64),
            data=np.array(data, dtype=np.complex128),
            shape=(len(target_irvec), component.shape[1], component.shape[2]),
        )

    @staticmethod
    def decompose_ham(hrs: np.ndarray, component: SparseCOO) -> np.complex128:
        if component.nnz == 0:
            return np.complex128(0.0)
        dense = component.todense()
        return np.complex128(np.einsum("rij,rij->", np.conjugate(dense), hrs))

    def reconstruct(self, indices: np.ndarray | None = None) -> np.ndarray:
        """Reconstruct a Hamiltonian from all or selected multipole components."""

        selected = set(range(self.num_multipole)) if indices is None else set(map(int, indices))
        hrs = np.zeros((self.nrpts, self.num_wann, self.num_wann), dtype=np.complex128)
        for im in selected:
            mask = self.coords[0] == im
            component = SparseCOO(
                coords=self.coords[1:, mask],
                data=self.data[mask],
                shape=(self.nrpts, self.num_wann, self.num_wann),
            )
            hrs += self.z_coefficients[im] * component.todense()
        return hrs

    def write_hdf5(self, hdf5_path: Path | str) -> None:
        """Write decomposition coefficients and padded multipole matrices."""

        with h5py.File(hdf5_path, "w") as h5:
            h5.create_dataset("irvec", data=self.irvec)
            h5.create_dataset("ndegen", data=self.ndegen)
            h5.create_dataset("z_coefficients", data=self.z_coefficients)
            grp = h5.create_group("multipole_padded")
            grp.create_dataset("shape", data=np.array(self.shape, dtype=np.int64))
            grp.create_dataset("coords", data=self.coords)
            grp.create_dataset("data", data=self.data)
            grp.create_dataset("im_order", data=self.coords[0].astype(np.int64))

