"""Tests that enforce the reproducibility-first figure policy."""

from __future__ import annotations

import csv
import json
import os
from pathlib import Path
import re
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
HEAVY_SMOKE_EXCLUSIONS = {
    "scripts/reproduce_figures/plot_bcc_planes.py",
    "scripts/reproduce_figures/plot_band_bond.py",
}


def manuscript_figure_files() -> list[str]:
    """Return all PDF figure paths referenced by LaTeX includegraphics commands."""
    text = (ROOT / "main_all.tex").read_text(encoding="utf-8")
    return re.findall(r"\\includegraphics(?:\[[^\]]+\])?\{([^}]+\.pdf)\}", text)


def inventory_rows() -> list[dict[str, str]]:
    """Read the machine-readable manuscript figure inventory."""
    with (ROOT / "data" / "processed" / "figure_inventory.csv").open(
        newline="", encoding="utf-8"
    ) as handle:
        return list(csv.DictReader(handle))


def reproducible_plot_rows() -> list[dict[str, str]]:
    """Return only figures that must be emitted by repository plotting scripts."""
    return [
        row
        for row in inventory_rows()
        if row["reproduction_category"] == "reproducible_plot"
    ]


def test_figure_inventory_matches_manuscript() -> None:
    """Verify that every manuscript figure has an explicit repository policy row."""
    figures = set(manuscript_figure_files())
    rows = inventory_rows()
    assert {row["figure_file"] for row in rows} == figures
    assert len(rows) == len(figures)


def test_inventory_has_no_included_static_assets() -> None:
    """Require included PDFs to be generated by repository plotting scripts."""
    allowed_categories = {
        "reproducible_plot",
        "workflow_required",
        "not_included",
    }
    rows = inventory_rows()
    for row in rows:
        assert row["reproduction_category"] in allowed_categories
        assert (ROOT / row["processed_data"]).exists()
        assert (ROOT / row["plotting_script"]).exists()
        if row["reproduction_category"] == "reproducible_plot":
            assert row["included_pdf"]
            assert (ROOT / row["included_pdf"]).is_file()
            assert row["generated_output"].startswith("results/figures/")
            assert row["plotting_script"].endswith(".py")
        else:
            assert row["included_pdf"] == ""
            assert row["generated_output"] == ""


def test_paper_directory_contains_only_reproducible_inventory_pdfs() -> None:
    """Ensure no untracked static manuscript assets remain under `figures/paper/`."""
    rows = inventory_rows()
    included = sorted(row["included_pdf"] for row in rows if row["included_pdf"])
    paper_pdfs = sorted(
        str(path.relative_to(ROOT)) for path in (ROOT / "figures" / "paper").glob("*.pdf")
    )
    assert paper_pdfs == included
    assert all(
        row["reproduction_category"] == "reproducible_plot"
        for row in rows
        if row["included_pdf"]
    )


def test_committed_paper_figures_are_small() -> None:
    """Enforce the repository policy that committed figure PDFs stay below 100 MB."""
    limit = 100 * 1024 * 1024
    oversized = [
        path
        for path in (ROOT / "figures" / "paper").glob("*.pdf")
        if path.stat().st_size > limit
    ]
    assert oversized == []


def test_reproduce_all_figures_check_mode() -> None:
    """Smoke-check figure reproduction inputs, sources, and scripts without plotting."""
    result = subprocess.run(
        ["bash", str(ROOT / "scripts" / "reproduce_all_figures.sh"), "--check"],
        check=True,
        capture_output=True,
        text=True,
    )
    assert "processed and source inputs" in result.stdout


def test_reproducible_plot_scripts_generate_nonempty_pdfs_except_bcc_planes(
    tmp_path: Path,
) -> None:
    """Run reproducible plotting scripts, excluding the known heavy plot jobs."""

    env = os.environ.copy()
    env["MPLBACKEND"] = "Agg"
    env.setdefault("PYTHONHASHSEED", "0")
    env["MPLCONFIGDIR"] = str(tmp_path / "mplconfig")
    env["PYTHON"] = sys.executable
    grouped_rows: dict[str, list[dict[str, str]]] = {}
    for row in reproducible_plot_rows():
        if row["plotting_script"] in HEAVY_SMOKE_EXCLUSIONS:
            continue
        grouped_rows.setdefault(row["plotting_script"], []).append(row)

    for script_rel, rows in grouped_rows.items():
        output_dir = tmp_path / Path(script_rel).stem
        result = subprocess.run(
            [
                sys.executable,
                str(ROOT / script_rel),
                "--output-dir",
                str(output_dir),
            ],
            check=True,
            capture_output=True,
            text=True,
            env=env,
            timeout=120,
        )
        assert result.returncode == 0

        expected_names = sorted(Path(row["generated_output"]).name for row in rows)
        generated_names = sorted(path.name for path in output_dir.glob("*.pdf"))
        assert generated_names == expected_names

        for row in rows:
            generated = output_dir / Path(row["generated_output"]).name
            reference = ROOT / row["included_pdf"]
            assert generated.is_file()
            data = generated.read_bytes()
            assert data.startswith(b"%PDF-")
            size = generated.stat().st_size
            reference_size = reference.stat().st_size
            assert size >= 1500
            assert size >= int(reference_size * 0.05)


def test_multipole_workflow_manifest_records_archived_hdf5_route() -> None:
    """Keep the archived HDF5-generation provenance for multipole bars explicit."""
    manifest = json.loads(
        (
            ROOT
            / "data/source/workflow_manifests/multipole_coefficients/workflow_manifest.json"
        ).read_text(encoding="utf-8")
    )
    assert manifest["source_status"]["direct_hdf5_present"] is False
    assert manifest["source_status"]["vector_snapshot_present"] is True
    assert manifest["archived_workflows"][0]["decomposition_output"] == "trs_py_ed_tb.hdf5"
    assert manifest["archived_workflows"][1]["decomposition_output"] == "trs_py_ed_hr.hdf5"
    assert manifest["label_selection"]["selected_z_count"] == 10


def test_processed_csv_files_have_source_chain() -> None:
    """Require every processed CSV to have a committed source or fallback provenance."""
    processed_csvs = {
        path.relative_to(ROOT)
        for path in (ROOT / "data" / "processed").rglob("*.csv")
        if path.name != "figure_inventory.csv"
    }
    export_backed = {
        Path("data/processed/ahc_111/ahc_angle_dependence.csv"),
        Path("data/processed/ahc_111/energy_angle_dependence.csv"),
        Path("data/processed/ahc_103/ahc_angle_dependence.csv"),
        Path("data/processed/ahc_103/energy_angle_dependence.csv"),
        Path("data/processed/rank_resolved_103/rank_resolved_ahc.csv"),
        Path("data/processed/rank_resolved_103/rank_cumulative_energy.csv"),
        Path("data/processed/rank_resolved_103/single_rank_ahc.csv"),
        Path("data/processed/strain_103/strain_plus_ahc.csv"),
        Path("data/processed/strain_103/strain_minus_ahc.csv"),
        Path("data/processed/minimal_model/model_sigma_axis.csv"),
    }
    pdf_vector_backed = {
        Path("data/processed/band_bond/band_bond_curves.csv"),
        Path("data/processed/multipole_coefficients/multipole_coefficients.csv"),
    }
    assert processed_csvs == export_backed | pdf_vector_backed

    for processed in export_backed:
        source = Path("data/source/production_exports") / processed.relative_to(
            "data/processed"
        )
        assert (ROOT / source).is_file(), f"{processed} has no source export"

    assert (ROOT / "data/source/pdf_vector/README.md").is_file()
    assert (
        ROOT
        / "data/source/pdf_vector/multipole_coefficients/multipole_coefficients.csv"
    ).is_file()
    assert (
        ROOT / "data/source/pdf_vector/multipole_coefficients/README.md"
    ).is_file()
    assert (
        ROOT
        / "data/source/workflow_manifests/multipole_coefficients/workflow_manifest.json"
    ).is_file()
    assert (
        ROOT
        / "data/source/workflow_manifests/multipole_coefficients/selected_z_ids.csv"
    ).is_file()
    assert (
        ROOT / "data/source/production_exports/minimal_model/model_sigma_axis.csv"
    ).is_file()
    assert (ROOT / "examples/minimal_model/model.py").is_file()
    assert (ROOT / "data/source/pdf_vector/band_bond/README.md").is_file()
    for source_pdf in [
        "data/source/pdf_vector/band_bond/band_1.pdf",
        "data/source/pdf_vector/band_bond/band_2.pdf",
        "data/source/pdf_vector/band_bond/band_3.pdf",
        "data/source/pdf_vector/band_bond/band_4.pdf",
        "data/source/pdf_vector/band_bond/band_5.pdf",
        "data/source/pdf_vector/band_bond/band_10.pdf",
        "data/source/pdf_vector/band_bond/band_20.pdf",
        "data/source/pdf_vector/band_bond/band_35.pdf",
        "figures/paper/bar_ed_all_35.pdf",
        "figures/paper/bar_ed_wo_q_35.pdf",
    ]:
        assert (ROOT / source_pdf).is_file()
