"""Tests that enforce the reproducibility-first figure policy."""

from __future__ import annotations

import csv
import importlib.util
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
HEAVY_SMOKE_EXCLUSIONS = {
    "scripts/reproduce_figures/plot_bcc_planes.py",
    "scripts/reproduce_figures/plot_band_bond.py",
}


def manuscript_figure_files() -> list[str]:
    """Return all PDF figure paths referenced by LaTeX includegraphics commands."""
    text = (ROOT / "main_all.tex").read_text(encoding="utf-8")
    return re.findall(r"\\includegraphics(?:\[[^\]]+\])?\{([^}]+\.pdf)\}", text)


def inventory_rows() -> list[dict[str, str]]:
    """Read the machine-readable manuscript figure inventory."""
    with (ROOT / "data" / "processed" / "figure_inventory.csv").open(
        newline="", encoding="utf-8"
    ) as handle:
        return list(csv.DictReader(handle))


def reproducible_plot_rows() -> list[dict[str, str]]:
    """Return only figures that must be emitted by repository plotting scripts."""
    return [
        row
        for row in inventory_rows()
        if row["reproduction_category"] == "reproducible_plot"
    ]


def fit_ahc_contract() -> dict[str, object]:
    return json.loads(
        (
            ROOT
            / "data/source/workflow_manifests/ahc/fit_ahc_reference_contract.json"
        ).read_text(encoding="utf-8")
    )


def rank_resolved_contract() -> dict[str, object]:
    return json.loads(
        (
            ROOT
            / "data/source/workflow_manifests/rank_resolved_103/rank_resolved_reference_contract.json"
        ).read_text(encoding="utf-8")
    )


def strain_contract() -> dict[str, object]:
    return json.loads(
        (
            ROOT
            / "data/source/workflow_manifests/strain_103/strain_reference_contract.json"
        ).read_text(encoding="utf-8")
    )


def minimal_model_contract() -> dict[str, object]:
    return json.loads(
        (
            ROOT
            / "data/source/workflow_manifests/minimal_model/minimal_model_reference_contract.json"
        ).read_text(encoding="utf-8")
    )


def band_bond_contract() -> dict[str, object]:
    return json.loads(
        (
            ROOT
            / "data/source/workflow_manifests/band_bond/band_bond_reference_contract.json"
        ).read_text(encoding="utf-8")
    )


def multipole_bar_contract() -> dict[str, object]:
    return json.loads(
        (
            ROOT
            / "data/source/workflow_manifests/multipole_coefficients/bar_plot_reference_contract.json"
        ).read_text(encoding="utf-8")
    )


def definitions_contract() -> dict[str, object]:
    return json.loads(
        (
            ROOT
            / "data/source/workflow_manifests/definitions/bcc_planes_reference_contract.json"
        ).read_text(encoding="utf-8")
    )


def pdf_strings(path: Path) -> str:
    """Extract plain strings from a generated PDF for lightweight label checks."""
    result = subprocess.run(
        ["strings", str(path)],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout


def load_script_module(script_rel: str, module_name: str):
    """Load a standalone plotting script as a module for config-level assertions."""
    script_path = ROOT / script_rel
    sys.path.insert(0, str(script_path.parent))
    try:
        spec = importlib.util.spec_from_file_location(module_name, script_path)
        assert spec is not None
        assert spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module
    finally:
        sys.path.pop(0)


def test_figure_inventory_matches_manuscript() -> None:
    """Verify that every manuscript figure has an explicit repository policy row."""
    figures = set(manuscript_figure_files())
    rows = inventory_rows()
    assert {row["figure_file"] for row in rows} == figures
    assert len(rows) == len(figures)


def test_inventory_has_no_included_static_assets() -> None:
    """Require included PDFs to be generated by repository plotting scripts."""
    allowed_categories = {
        "reproducible_plot",
        "workflow_required",
        "not_included",
    }
    rows = inventory_rows()
    for row in rows:
        assert row["reproduction_category"] in allowed_categories
        assert (ROOT / row["processed_data"]).exists()
        assert (ROOT / row["plotting_script"]).exists()
        if row["reproduction_category"] == "reproducible_plot":
            assert row["included_pdf"]
            assert (ROOT / row["included_pdf"]).is_file()
            assert row["generated_output"].startswith("results/figures_paper/")
            assert row["plotting_script"].endswith(".py")
        else:
            assert row["included_pdf"] == ""
            assert row["generated_output"] == ""


def test_paper_directory_contains_only_reproducible_inventory_pdfs() -> None:
    """Ensure no untracked static manuscript assets remain under `figures/paper/`."""
    rows = inventory_rows()
    included = sorted(row["included_pdf"] for row in rows if row["included_pdf"])
    paper_pdfs = sorted(
        str(path.relative_to(ROOT)) for path in (ROOT / "figures" / "paper").glob("*.pdf")
    )
    assert paper_pdfs == included
    assert all(
        row["reproduction_category"] == "reproducible_plot"
        for row in rows
        if row["included_pdf"]
    )


def test_committed_paper_figures_are_small() -> None:
    """Enforce the repository policy that committed figure PDFs stay below 100 MB."""
    limit = 100 * 1024 * 1024
    oversized = [
        path
        for path in (ROOT / "figures" / "paper").glob("*.pdf")
        if path.stat().st_size > limit
    ]
    assert oversized == []


def test_reproduce_all_figures_check_mode() -> None:
    """Smoke-check figure reproduction inputs, sources, and scripts without plotting."""
    result = subprocess.run(
        ["bash", str(ROOT / "scripts" / "reproduce_all_figures.sh"), "--check"],
        check=True,
        capture_output=True,
        text=True,
    )
    assert "processed and source inputs" in result.stdout


def test_reproducible_plot_scripts_generate_nonempty_pdfs_except_bcc_planes(
    tmp_path: Path,
) -> None:
    """Run reproducible plotting scripts, excluding the known heavy plot jobs."""

    env = os.environ.copy()
    env["MPLBACKEND"] = "Agg"
    env.setdefault("PYTHONHASHSEED", "0")
    env["MPLCONFIGDIR"] = str(tmp_path / "mplconfig")
    env["PYTHON"] = sys.executable

    # Warm the shared Matplotlib cache once so the per-script subprocess
    # timeout tracks plotting work rather than first-import font discovery.
    subprocess.run(
        [sys.executable, "-c", "import matplotlib; import matplotlib.pyplot"],
        check=True,
        capture_output=True,
        text=True,
        env=env,
        timeout=180,
    )

    grouped_rows: dict[str, list[dict[str, str]]] = {}
    for row in reproducible_plot_rows():
        if row["plotting_script"] in HEAVY_SMOKE_EXCLUSIONS:
            continue
        grouped_rows.setdefault(row["plotting_script"], []).append(row)

    for script_rel, rows in grouped_rows.items():
        output_dir = tmp_path / Path(script_rel).stem
        result = subprocess.run(
            [
                sys.executable,
                str(ROOT / script_rel),
                "--output-dir",
                str(output_dir),
            ],
            check=True,
            capture_output=True,
            text=True,
            env=env,
            timeout=180,
        )
        assert result.returncode == 0

        expected_names = sorted(Path(row["generated_output"]).name for row in rows)
        generated_names = sorted(path.name for path in output_dir.glob("*.pdf"))
        assert generated_names == expected_names

        for row in rows:
            generated = output_dir / Path(row["generated_output"]).name
            reference = ROOT / row["included_pdf"]
            assert generated.is_file()
            data = generated.read_bytes()
            assert data.startswith(b"%PDF-")
            size = generated.stat().st_size
            reference_size = reference.stat().st_size
            assert size >= 1500
            assert size >= int(reference_size * 0.05)

        if script_rel == "scripts/reproduce_figures/plot_rank_resolved_103.py":
            sample_pdf = output_dir / expected_names[0]
            text = pdf_strings(sample_pdf)
            assert "w_rank" not in text
            assert "SW+ED" not in text
        if script_rel == "scripts/reproduce_figures/plot_multipole_coefficients.py":
            sample_pdf = output_dir / expected_names[0]
            text = pdf_strings(sample_pdf)
            assert "Q electric" not in text
            assert "M magnetic" not in text
            assert "T magnetic-toroidal" not in text


def test_ahc_paper_configs_follow_archived_fit_source_roles() -> None:
    """Paper-mode fit_ahc plots should expose reference-PDF series roles honestly."""
    for module_name, script_rel in [
        ("plot_ahc_111_module", "scripts/reproduce_figures/plot_ahc_111.py"),
        ("plot_ahc_103_module", "scripts/reproduce_figures/plot_ahc_103.py"),
    ]:
        module = load_script_module(script_rel, module_name)
        config = module.paper_plot_config("para")
        assert config["methods"] == ["SW+ED", "Wan90"]
        assert config["label_map"]["SW+ED"] == "model"
        assert config["label_map"]["Wan90"] == "DFT"
        assert config["label_map"]["fitting"] == "fitting"
        assert config["style_map"]["SW+ED"]["linestyle"] == "--"
        assert config["style_map"]["Wan90"]["marker"] == "D"
        assert "results/figures_paper/" in str(module.output_dir_for("paper"))


def test_fit_ahc_reference_contract_matches_public_paper_roles() -> None:
    """The AHC contract should match the public paper-facing role mapping."""
    contract = fit_ahc_contract()
    assert sorted(contract["panels"]) == [
        "103:axis",
        "103:para",
        "103:perp",
        "111:axis",
        "111:para",
        "111:perp",
    ]
    evidence = contract["reference_evidence"]
    assert "fit_ahc.py" in " ".join(evidence["reference_scripts"])
    assert "plot_ahc.py" in " ".join(evidence["reference_scripts"])
    for panel_key, panel in contract["panels"].items():
        assert panel["paper_reproducible"] is True
        series = panel["required_series"]
        assert [item["paper_label"] for item in series] == ["model", "fitting"]
        assert series[0]["source_method"] == "SW+ED"
        assert series[0]["min_finite_points"] == 13
        assert series[1]["min_finite_points"] == 181
        optional = panel["optional_series"]
        assert len(optional) == 1
        assert optional[0]["paper_label"] == "DFT"
        assert optional[0]["source_method"] == "Wan90"


def test_fit_ahc_processed_data_satisfies_contract() -> None:
    """Current compact AHC sources should satisfy the fit_ahc paper contract."""
    contract = fit_ahc_contract()["panels"]
    for plane in ["111", "103"]:
        with (ROOT / f"data/processed/ahc_{plane}/ahc_angle_dependence.csv").open(
            newline="", encoding="utf-8"
        ) as handle:
            rows = list(csv.DictReader(handle))
        for component in ["para", "perp", "axis"]:
            panel = contract[f"{plane}:{component}"]
            requirement = panel["required_series"][0]
            finite = sum(
                1
                for row in rows
                if row["method"] == requirement["source_method"]
                and row[requirement["source_column"]].strip().lower() != "nan"
            )
            assert finite == 13
            optional = panel["optional_series"][0]
            optional_finite = sum(
                1
                for row in rows
                if row["method"] == optional["source_method"]
                and row[optional["source_column"]].strip().lower() != "nan"
            )
            assert optional_finite == optional["min_finite_points"]


def test_fit_ahc_optional_dft_overlay_matches_compact_availability() -> None:
    """Optional DFT overlays should reflect the actual compact-source coverage."""
    expected = {"111": 0, "103": 5}
    for plane, target in expected.items():
        with (ROOT / f"data/processed/ahc_{plane}/ahc_angle_dependence.csv").open(
            newline="", encoding="utf-8"
        ) as handle:
            rows = list(csv.DictReader(handle))
        for column in ["sigma_para_s_cm", "sigma_perp_s_cm", "sigma_axis_s_cm"]:
            finite = sum(
                1
                for row in rows
                if row["method"] == "Wan90" and row[column].strip().lower() != "nan"
            )
            assert finite == target


def test_rank_resolved_paper_config_uses_manuscript_series_roles() -> None:
    """Paper-mode rank-resolved plots should expose manuscript-facing multipole labels."""
    module = load_script_module(
        "scripts/reproduce_figures/plot_rank_resolved_103.py",
        "plot_rank_resolved_103_module",
    )
    assert module.display_label("w_rank1", style="paper", single_rank=False) == r"$\mathbb{M}_1$"
    assert (
        module.display_label("w_rank1_2_3_4", style="paper", single_rank=False)
        == r"$\mathbb{M}_1 + \mathbb{T}_2 + \mathbb{M}_3 + \mathbb{T}_4$"
    )
    assert module.display_label("w_rank4", style="paper", single_rank=True) == r"$\mathbb{T}_4$"
    assert module.reference_label("paper") == "all ranks"
    assert module.component_ylabel("axis", style="paper") == r"$\sigma_{n}\ [\mathrm{S/cm}]$"
    assert "results/figures_paper/" in str(module.output_dir_for("paper"))


def test_rank_resolved_reference_contract_matches_paper_config() -> None:
    """The rank-resolved contract should mirror the public paper-facing plot roles."""
    module = load_script_module(
        "scripts/reproduce_figures/plot_rank_resolved_103.py",
        "plot_rank_resolved_103_contract_module",
    )
    contract = rank_resolved_contract()

    assert sorted(contract["components"]) == ["axis", "para", "perp"]
    assert sorted(contract["panel_sets"]) == ["group1", "group2", "group3", "single_rank"]

    cumulative_methods = [panel["required_series"][:2] for key, panel in contract["panel_sets"].items() if key.startswith("group")]
    assert [[item["source_method"] for item in pair] for pair in cumulative_methods] == module.GROUPS
    assert [item["source_method"] for item in contract["panel_sets"]["single_rank"]["required_series"][:4]] == module.SINGLE_RANK_METHODS

    for component, meta in contract["components"].items():
        assert meta["paper_ylabel"] == module.component_ylabel(component, style="paper")

    for panel_key, panel in contract["panel_sets"].items():
        single_rank = panel_key == "single_rank"
        expected_reference = panel["required_series"][-1]
        assert expected_reference["source_method"] == "SW+ED"
        assert expected_reference["paper_label"] == module.reference_label("paper")
        for requirement in panel["required_series"][:-1]:
            assert requirement["paper_label"] == module.display_label(
                requirement["source_method"],
                style="paper",
                single_rank=single_rank,
            )
        for component, output in panel["panel_outputs"].items():
            assert output["generated_output"].startswith("results/figures_paper/rank_resolved_103/")
            assert output["figure_file"].endswith(".pdf")
            expected_name = (
                f"sigma_{component}.pdf" if single_rank else f"sigma_{component}_{panel_key}.pdf"
            )
            assert output["figure_file"] == expected_name


def test_rank_resolved_processed_data_satisfies_contract() -> None:
    """Committed compact rank-resolved sources should satisfy the paper contract."""
    contract = rank_resolved_contract()
    components = contract["components"]

    for panel_key, panel in contract["panel_sets"].items():
        with (ROOT / panel["source_csv"]).open(newline="", encoding="utf-8") as handle:
            rows = list(csv.DictReader(handle))
        for component, component_meta in components.items():
            source_column = component_meta["source_column"]
            for requirement in panel["required_series"]:
                matching_rows = [
                    row
                    for row in rows
                    if row["series_group"] == requirement["series_group"]
                    and row["method"] == requirement["source_method"]
                    and row[source_column].strip().lower() != "nan"
                ]
                finite_points = len(matching_rows)
                assert finite_points == requirement["min_finite_points"]
                x_grid = sorted({int(float(row["phi_deg"])) for row in matching_rows})
                assert x_grid == requirement["x_grid_deg"]


def test_strain_paper_config_matches_reference_contract() -> None:
    """The strain contract should match the public paper-facing strain plot role."""
    module = load_script_module(
        "scripts/reproduce_figures/plot_strain_103.py",
        "plot_strain_103_contract_module",
    )
    contract = strain_contract()

    assert contract["component"]["source_column"] == module.PAPER_COMPONENT_COLUMN
    assert contract["component"]["paper_ylabel"] == module.PAPER_YLABEL
    assert contract["component"]["paper_xlabel"] == module.PAPER_XLABEL

    for branch_name, branch in contract["branches"].items():
        assert branch["required_method"] == module.PAPER_METHOD
        assert branch["title"] == module.BRANCH_TITLES[branch_name]
        assert branch["generated_output"].startswith("results/figures_paper/strain_103/")
        assert branch["figure_file"].endswith(".pdf")


def test_strain_processed_data_satisfies_contract() -> None:
    """Committed compact strain-response sources should satisfy the paper contract."""
    contract = strain_contract()
    source_column = contract["component"]["source_column"]

    for branch_name, branch in contract["branches"].items():
        with (ROOT / branch["source_csv"]).open(newline="", encoding="utf-8") as handle:
            rows = list(csv.DictReader(handle))

        strain_values = sorted(
            {
                float(row["strain_percent"])
                for row in rows
                if row["method"] == branch["required_method"]
                and row[source_column].strip().lower() != "nan"
            }
        )
        assert strain_values == branch["required_strain_values_percent"]

        for strain_value in strain_values:
            matching_rows = [
                row
                for row in rows
                if row["method"] == branch["required_method"]
                and float(row["strain_percent"]) == strain_value
                and row[source_column].strip().lower() != "nan"
            ]
            assert len(matching_rows) == branch["min_finite_points_per_strain"]
            x_grid = sorted({int(float(row["phi_deg"])) for row in matching_rows})
            assert x_grid == branch["x_grid_deg"]


def test_minimal_model_paper_config_matches_reference_contract() -> None:
    """The minimal-model contract should match the public paper-facing plot role."""
    module = load_script_module(
        "scripts/reproduce_figures/plot_minimal_model.py",
        "plot_minimal_model_contract_module",
    )
    contract = minimal_model_contract()

    assert contract["component"]["source_column"] == "sigma_axis"
    assert contract["component"]["paper_ylabel"] == module.PAPER_YLABEL
    assert contract["component"]["paper_xlabel"] == module.PAPER_XLABEL
    assert contract["scans"]["first_nn"]["figure_file"] == module.SCAN_OUTPUTS["first_nn"]
    assert contract["scans"]["second_nn"]["figure_file"] == module.SCAN_OUTPUTS["second_nn"]
    for scan_name, scan in contract["scans"].items():
        assert scan["generated_output"].startswith("results/figures_paper/minimal_model/")


def test_minimal_model_processed_data_satisfies_contract() -> None:
    """Committed compact minimal-model source should satisfy the paper contract."""
    contract = minimal_model_contract()
    source_column = contract["component"]["source_column"]

    with (ROOT / contract["scans"]["first_nn"]["source_csv"]).open(
        newline="", encoding="utf-8"
    ) as handle:
        rows = list(csv.DictReader(handle))

    for scan_name, scan in contract["scans"].items():
        subset = [row for row in rows if row["scan"] == scan_name]
        parameter_values = sorted(
            {
                float(row["parameter_value"])
                for row in subset
                if row[source_column].strip().lower() != "nan"
            }
        )
        assert parameter_values == scan["required_parameter_values"]

        for parameter_value in parameter_values:
            matching_rows = [
                row
                for row in subset
                if float(row["parameter_value"]) == parameter_value
                and row[source_column].strip().lower() != "nan"
            ]
            assert len(matching_rows) == scan["min_finite_points_per_parameter"]
            x_grid = sorted({int(float(row["phi_deg"])) for row in matching_rows})
            assert x_grid == scan["x_grid_deg"]


def test_band_bond_paper_config_matches_reference_contract() -> None:
    """The band/bond contract should match the public paper-facing composite role."""
    module = load_script_module(
        "scripts/reproduce_figures/plot_band_bond.py",
        "plot_band_bond_contract_module",
    )
    contract = band_bond_contract()

    assert contract["figure_file"] == "band_bond.pdf"
    assert contract["generated_output"] == "results/figures_paper/band_bond/band_bond.pdf"
    assert contract["paper_cutoffs"] == module.PAPER_CUTOFFS
    assert contract["series"] == module.PAPER_SERIES
    assert tuple(contract["x_range"]) == module.PAPER_XRANGE
    assert tuple(contract["y_range"]) == module.PAPER_YRANGE
    assert contract["xtick_labels"] == module.XTICK_LABELS


def test_band_bond_processed_data_satisfies_contract() -> None:
    """Recovered compact band/bond curves should satisfy the paper contract."""
    contract = band_bond_contract()
    with (ROOT / contract["source_csv"]).open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))

    cutoffs_present = sorted({int(row["cutoff_shell"]) for row in rows})
    assert cutoffs_present == sorted(contract["paper_cutoffs"] + contract["excluded_cutoffs"])

    for cutoff in contract["paper_cutoffs"]:
        cutoff_rows = [row for row in rows if row["cutoff_shell"] == str(cutoff)]
        assert sorted({row["series"] for row in cutoff_rows}) == contract["series"]
        requirements = contract["required_curves"][str(cutoff)]
        for series in contract["series"]:
            series_rows = [row for row in cutoff_rows if row["series"] == series]
            curve_count = len({row["curve_index"] for row in series_rows})
            point_count = len(series_rows)
            assert curve_count == requirements[series]["curve_count"]
            assert point_count == requirements[series]["point_count"]
            x_values = [float(row["k_path_fraction"]) for row in series_rows]
            assert min(x_values) == contract["x_range"][0]
            assert max(x_values) == contract["x_range"][1]


def test_multipole_paper_config_uses_family_legend_and_short_labels() -> None:
    """Paper-mode multipole plots should match the manuscript-facing label and legend style."""
    module = load_script_module(
        "scripts/reproduce_figures/plot_multipole_coefficients.py",
        "plot_multipole_coefficients_module",
    )
    row = {
        "index": "86479",
        "name": "M(1,T1g,,0|1,-1)",
        "coefficient_ev": "-3.80923944",
    }
    assert module.paper_label(row) == "z86479 M(1,T1g,,0|1,-1)"
    assert module.diagnostic_label(row) == "z_86479 M(1,T1g,,0|1,-1)"
    assert module.family_code(row["name"]) == "M"
    assert module.FAMILY_LABELS["T"] == "T"
    assert module.FAMILY_ROLE_LABELS["T"] == "T magnetic-toroidal"
    assert "results/figures_paper/" in str(module.output_dir_for("paper"))


def test_multipole_bar_contract_matches_paper_selection() -> None:
    """The multipole bar contract should match the public paper-facing selection rules."""
    module = load_script_module(
        "scripts/reproduce_figures/plot_multipole_coefficients.py",
        "plot_multipole_coefficients_contract_module",
    )
    contract = multipole_bar_contract()

    assert contract["paper_ylabel"] == "z [eV]"
    assert contract["paper_legend_labels"] == module.FAMILY_LABELS

    with (ROOT / contract["input_csv"]).open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))

    for figure_key, figure in contract["figures"].items():
        selected = module.select_rows(rows, exclude_q=figure["exclude_q"])
        assert len(selected) == figure["top_n"]
        assert [row["index"] for row in selected] == figure["required_indices"]
        assert [module.family_code(row["name"]) for row in selected] == figure["required_families"]
        assert figure["generated_output"].startswith("results/figures_paper/multipole_coefficients/")


def test_bcc_definition_contract_matches_processed_json_and_script() -> None:
    """The geometric contract should match the committed plane-definition JSON."""
    module = load_script_module(
        "scripts/reproduce_figures/plot_bcc_planes.py",
        "plot_bcc_planes_contract_module",
    )
    contract = definitions_contract()

    assert contract["generated_output_root"] == "results/figures_paper/definitions/"
    assert str(module.DEFAULT_OUTPUT).endswith("results/figures_paper/definitions")
    assert sorted(module.REQUIRED_CONFIG_KEYS) == sorted(
        [
            "id",
            "title",
            "output_file",
            "psi_deg",
            "plane_normal",
            "reference_vector",
            "reference_label",
            "perpendicular_vector",
            "perpendicular_label",
        ]
    )

    configs = {
        config["id"]: config
        for config in json.loads((ROOT / contract["input_json"]).read_text(encoding="utf-8"))["planes"]
    }
    assert sorted(configs) == sorted(contract["planes"])

    for plane_id, plane in contract["planes"].items():
        config = configs[plane_id]
        assert config["output_file"] == plane["figure_file"]
        for key in [
            "psi_deg",
            "plane_normal",
            "reference_vector",
            "reference_label",
            "perpendicular_vector",
            "perpendicular_label",
        ]:
            assert config[key] == plane[key]
        assert plane["generated_output"].startswith("results/figures_paper/definitions/")


def test_contact_sheet_script_maps_inventory_to_paper_outputs() -> None:
    """The contact-sheet helper should pair each reproducible plot with its paper output."""
    module = load_script_module(
        "scripts/reproduce_figures/make_paper_contact_sheet.py",
        "make_paper_contact_sheet_module",
    )
    pairs = module.reproducible_pairs()
    rows = reproducible_plot_rows()
    assert len(pairs) == len(rows)
    assert pairs[0].reference_pdf == ROOT / rows[0]["included_pdf"]
    generated_rel = Path(rows[0]["generated_output"]).relative_to("results/figures_paper")
    assert pairs[0].generated_rel == generated_rel
    assert pairs[0].generated_pdf == ROOT / "results" / "figures_paper" / generated_rel
    assert module.DEFAULT_CONTACT_SHEET_OUTPUT == (
        ROOT / "results" / "figures_diagnostics" / "contact_sheets" / "paper_vs_reference.pdf"
    )


def test_contact_sheet_script_uses_ghostscript_when_available() -> None:
    """Keep the contact-sheet dependency explicit so failures are easy to interpret."""
    module = load_script_module(
        "scripts/reproduce_figures/make_paper_contact_sheet.py",
        "make_paper_contact_sheet_gs_module",
    )
    if shutil.which("gs") is None:
        try:
            module.require_ghostscript()
        except RuntimeError as exc:
            assert "Ghostscript" in str(exc)
        else:
            raise AssertionError("Expected Ghostscript lookup to fail when gs is absent")
    else:
        assert module.require_ghostscript().endswith("gs")


def test_multipole_workflow_manifest_records_archived_hdf5_route() -> None:
    """Keep the archived HDF5-generation provenance for multipole bars explicit."""
    manifest = json.loads(
        (
            ROOT
            / "data/source/workflow_manifests/multipole_coefficients/workflow_manifest.json"
        ).read_text(encoding="utf-8")
    )
    assert manifest["source_status"]["direct_hdf5_present"] is False
    assert manifest["source_status"]["vector_snapshot_present"] is True
    assert manifest["archived_workflows"][0]["decomposition_output"] == "trs_py_ed_tb.hdf5"
    assert manifest["archived_workflows"][1]["decomposition_output"] == "trs_py_ed_hr.hdf5"
    assert manifest["label_selection"]["selected_z_count"] == 10


def test_processed_csv_files_have_source_chain() -> None:
    """Require every processed CSV to have a committed source or fallback provenance."""
    processed_csvs = {
        path.relative_to(ROOT)
        for path in (ROOT / "data" / "processed").rglob("*.csv")
        if path.name != "figure_inventory.csv"
    }
    export_backed = {
        Path("data/processed/ahc_111/ahc_angle_dependence.csv"),
        Path("data/processed/ahc_111/energy_angle_dependence.csv"),
        Path("data/processed/ahc_103/ahc_angle_dependence.csv"),
        Path("data/processed/ahc_103/energy_angle_dependence.csv"),
        Path("data/processed/rank_resolved_103/rank_resolved_ahc.csv"),
        Path("data/processed/rank_resolved_103/rank_cumulative_energy.csv"),
        Path("data/processed/rank_resolved_103/single_rank_ahc.csv"),
        Path("data/processed/strain_103/strain_plus_ahc.csv"),
        Path("data/processed/strain_103/strain_minus_ahc.csv"),
        Path("data/processed/minimal_model/model_sigma_axis.csv"),
    }
    pdf_vector_backed = {
        Path("data/processed/band_bond/band_bond_curves.csv"),
        Path("data/processed/multipole_coefficients/multipole_coefficients.csv"),
    }
    assert processed_csvs == export_backed | pdf_vector_backed

    for processed in export_backed:
        source = Path("data/source/production_exports") / processed.relative_to(
            "data/processed"
        )
        assert (ROOT / source).is_file(), f"{processed} has no source export"

    assert (ROOT / "data/source/pdf_vector/README.md").is_file()
    assert (
        ROOT
        / "data/source/pdf_vector/multipole_coefficients/multipole_coefficients.csv"
    ).is_file()
    assert (
        ROOT / "data/source/pdf_vector/multipole_coefficients/README.md"
    ).is_file()
    assert (
        ROOT
        / "data/source/workflow_manifests/multipole_coefficients/workflow_manifest.json"
    ).is_file()
    assert (
        ROOT
        / "data/source/workflow_manifests/multipole_coefficients/selected_z_ids.csv"
    ).is_file()
    assert (
        ROOT / "data/source/production_exports/minimal_model/model_sigma_axis.csv"
    ).is_file()
    assert (ROOT / "examples/minimal_model/model.py").is_file()
    assert (ROOT / "data/source/pdf_vector/band_bond/README.md").is_file()
    for source_pdf in [
        "data/source/pdf_vector/band_bond/band_1.pdf",
        "data/source/pdf_vector/band_bond/band_2.pdf",
        "data/source/pdf_vector/band_bond/band_3.pdf",
        "data/source/pdf_vector/band_bond/band_4.pdf",
        "data/source/pdf_vector/band_bond/band_5.pdf",
        "data/source/pdf_vector/band_bond/band_10.pdf",
        "data/source/pdf_vector/band_bond/band_20.pdf",
        "data/source/pdf_vector/band_bond/band_35.pdf",
        "figures/paper/bar_ed_all_35.pdf",
        "figures/paper/bar_ed_wo_q_35.pdf",
    ]:
        assert (ROOT / source_pdf).is_file()
