#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON_BIN="${PYTHON:-python}"
OUTPUT_ROOT="${1:-"$ROOT/results/figures"}"

check_only=0
if [[ "${1:-}" == "--check" ]]; then
  check_only=1
  OUTPUT_ROOT="$ROOT/results/figures"
fi

required_inputs=(
  "$ROOT/data/processed/ahc_111/ahc_angle_dependence.csv"
  "$ROOT/data/processed/ahc_103/ahc_angle_dependence.csv"
  "$ROOT/data/processed/rank_resolved_103/rank_resolved_ahc.csv"
  "$ROOT/data/processed/rank_resolved_103/single_rank_ahc.csv"
  "$ROOT/data/processed/strain_103/strain_plus_ahc.csv"
  "$ROOT/data/processed/strain_103/strain_minus_ahc.csv"
  "$ROOT/data/processed/multipole_coefficients/multipole_coefficients.csv"
  "$ROOT/data/processed/minimal_model/model_sigma_axis.csv"
)

required_sources=(
  "$ROOT/data/source/README.md"
  "$ROOT/data/source/production_exports/README.md"
  "$ROOT/data/source/production_exports/ahc_111/ahc_angle_dependence.csv"
  "$ROOT/data/source/production_exports/ahc_111/energy_angle_dependence.csv"
  "$ROOT/data/source/production_exports/ahc_103/ahc_angle_dependence.csv"
  "$ROOT/data/source/production_exports/ahc_103/energy_angle_dependence.csv"
  "$ROOT/data/source/production_exports/rank_resolved_103/rank_resolved_ahc.csv"
  "$ROOT/data/source/production_exports/rank_resolved_103/rank_cumulative_energy.csv"
  "$ROOT/data/source/production_exports/rank_resolved_103/single_rank_ahc.csv"
  "$ROOT/data/source/production_exports/strain_103/strain_plus_ahc.csv"
  "$ROOT/data/source/production_exports/strain_103/strain_minus_ahc.csv"
  "$ROOT/data/source/pdf_vector/README.md"
  "$ROOT/figures/paper/bar_ed_all_35.pdf"
  "$ROOT/figures/paper/bar_ed_wo_q_35.pdf"
  "$ROOT/figures/paper/sigma_axis_model_1st_nn.pdf"
  "$ROOT/figures/paper/sigma_axis_model_2nd_nn.pdf"
)

required_scripts=(
  "$ROOT/scripts/reproduce_figures/plot_ahc_111.py"
  "$ROOT/scripts/reproduce_figures/plot_ahc_103.py"
  "$ROOT/scripts/reproduce_figures/plot_rank_resolved_103.py"
  "$ROOT/scripts/reproduce_figures/plot_strain_103.py"
  "$ROOT/scripts/reproduce_figures/plot_multipole_coefficients.py"
  "$ROOT/scripts/reproduce_figures/plot_minimal_model.py"
)

missing=0
for path in "${required_inputs[@]}" "${required_sources[@]}" "${required_scripts[@]}"; do
  if [[ ! -e "$path" ]]; then
    echo "Missing required file: $path" >&2
    missing=1
  fi
done

if [[ "$missing" -ne 0 ]]; then
  exit 1
fi

if [[ "$check_only" -eq 1 ]]; then
  echo "Figure reproduction processed and source inputs and scripts are present."
  exit 0
fi

mkdir -p "$OUTPUT_ROOT"

"$PYTHON_BIN" "$ROOT/scripts/reproduce_figures/plot_ahc_111.py" \
  --output-dir "$OUTPUT_ROOT/ahc_111"
"$PYTHON_BIN" "$ROOT/scripts/reproduce_figures/plot_ahc_103.py" \
  --output-dir "$OUTPUT_ROOT/ahc_103"
"$PYTHON_BIN" "$ROOT/scripts/reproduce_figures/plot_rank_resolved_103.py" \
  --output-dir "$OUTPUT_ROOT/rank_resolved_103"
"$PYTHON_BIN" "$ROOT/scripts/reproduce_figures/plot_strain_103.py" \
  --output-dir "$OUTPUT_ROOT/strain_103"
"$PYTHON_BIN" "$ROOT/scripts/reproduce_figures/plot_multipole_coefficients.py" \
  --output-dir "$OUTPUT_ROOT/multipole_coefficients"
"$PYTHON_BIN" "$ROOT/scripts/reproduce_figures/plot_minimal_model.py" \
  --output-dir "$OUTPUT_ROOT/minimal_model"

cat <<EOF
Generated repository-local figures under:
  $OUTPUT_ROOT

Not generated by this lightweight repository path:
  band_bond.pdf requires the documented full Hamiltonian workflow and is not
  tracked as a figure PDF until compact source data and a plotting script are
  recovered.
EOF
